//Copyright 2026 Caleb Broodo
//GetFit, GetNParams, default parameters/limits, fit logging/statbo
#pragma once

#include <string>
#include <memory>
#include <utility>

#include "Models.h"

// ROOT
#include "TF1.h"
#include "TGraphErrors.h"
#include "TFitResultPtr.h"

namespace FitUtils {

  // Basic metadata
  int GetNParams(Models::Function f);
  const char* FunctionToString(Models::Function f);

  // Defaults for fits
  void SetDefaultParameters(TF1* fit, Models::Function f);
  void SetDefaultLimits(TF1* fit, Models::Function f);   // optional, but useful
  void SetParNames(TF1* fit, Models::Function f);        // optional

  // ---------------------------
  // TF1 builder ("GetFit")
  // ---------------------------
  //
  // Builds a TF1 that evaluates the chosen Models::Function on [xmin, xmax]
  // with the correct number of parameters.
  //
  // If applyDefaults=true, it sets default parameters (and limits if applyLimits=true).
  //
  TF1* MakeTF1(const std::string& name,
               Models::Function f,
               double xmin,
               double xmax,
               bool applyDefaults = true,
               bool applyLimits   = true);

  // Convenience overload with autogenerated name
  TF1* MakeTF1(Models::Function f,
               double xmin,
               double xmax,
               bool applyDefaults = true,
               bool applyLimits   = true);

  // ---------------------------
  // Fit wrappers (optional)
  // ---------------------------
  //
  // Fit a TGraphErrors with a TF1. Options are ROOT fit options string.
  // Example: options="QNR" (quiet, no draw, fit range).
  //
  TFitResultPtr FitGraph(TGraphErrors* g,
                         TF1* fit,
                         const std::string& options = "QNR");

  // Small helper: print basic fit status/chi2/ndf
  void PrintFitSummary(const TF1* fit, const char* label = nullptr);

} // namespace FitUtils

